### ISSUE TITLE
phiX filtering?

### ISSUE THREAD

**Issue by gregcaporaso** [benjjneb/q2-dada2#10]
@benjjneb, does the DADA2 script in this repo perform phiX filtering? I'm working on some test data, and seeing a lot of phiX in my data set after DADA2.

**Comment by benjjneb** [comment]
Not as currently written. It can be added to the `fastqFilter` call though, eg:

```S
fastqFilter(unfilts[i], filteredFastq, truncLen=truncLen, trimLeft=trimLeft, rm.phix=TRUE)
```

**Comment by gregcaporaso** [comment]
Thanks, I'll try this out!
