### ISSUE TITLE
integrate initial quality trimming into denoise or as a new method

### ISSUE THREAD

**Issue by gregcaporaso** [benjjneb/q2-dada2#3]

**Comment by benjjneb** [comment]
> Do you have a recommendation for what those defaults could be?

For forward Illumina reads, decent defaults for `fastqFilter` might be: `maxN=0`, `truncQ=2`, `maxEE=2`, `trimLeft=10` and `truncLen=seqlen - (seqlen %% 5)`

I think its very important to allow these parameters, especially `truncLen`, `trimLeft` and `maxEE` to be passed in by the user though. These will work well for decent-good quality Illumina data, but for poor quality data, or older short sequences, simple changes like raising `maxEE` or reducing `truncLen` can make a huge difference in the number of sequences that pass the filter at little-to-no cost in the quality of the denoised data.

**Comment by gregcaporaso** [comment]
Thanks. As I have it currently written, the user has control over these parameters. We can add these as defaults though.
